### ISSUE TITLE
Update .gitignore files

### ISSUE THREAD

**Issue by ChrisZhong** [nus-ncl/network-builder#7]
Only the required files should be in the repository. Files/directories that are created as part of Eclipse or the Gradle build does not need to be in the repository.

- `.gradle` directory
- `.settings` directory 
- `bin` directory
- `build` directory
- `.classpath` file
- `.project` file

**Comment by ChrisZhong** [comment]
Please delete said files from the repository as well.

**Comment by ChrisZhong** [comment]
There are still artifacts in the `src/main/java` and `src/main/java/createExpt` directories.

**Comment by desmondlim** [comment]
Removed the .settings, .classpath and .project from src/main/java.
Removed the .class files from src/main/java/createExpt.
Added *.class to .gitignore
